services:
    bagisto:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bagisto-app
        restart: unless-stopped
        volumes:
            - .:/var/www/bagisto
        expose:
            - "8000"
        depends_on:
            - db_bagisto
        networks:
            - bagisto

    db_bagisto:
        image: mysql:8.0
        container_name: db-bagisto
        restart: unless-stopped
        volumes:
            - bagisto_db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "bagisto"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
        networks:
            - bagisto

    nginx_bagisto:
        image: nginx:alpine
        container_name: nginx-bagisto-server
        restart: unless-stopped
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - .:/var/www/bagisto
        ports:
            - "80:80"
            - "8080:8080"
        depends_on:
            - bagisto
        networks:
            - bagisto

networks:
    bagisto:
        driver: bridge

volumes:
    bagisto_db_data:
